sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - PARSER=native
  - PARSER=lxml

matrix:
  allow_failures:
    - python: "3.4"
      env:
        - PARSER=native
        - VCR_RECORD_MODE=all
        - PYTEST_ADDOPTS="-m integration"

cache:
  directories:
    - $HOME/.cache/pip
    - tests/data/mkv

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -e .[test]
  - if [ $PARSER = "lxml" ]; then pip install lxml; fi
  - pip install coveralls

script: python setup.py test -a "--cov subliminal --verbose"

after_success: coveralls
