language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - PARSER=native
  - PARSER=lxml

install:
  - pip install .[test]
  - if [ $PARSER = "lxml" ]; then pip install lxml; fi
  - pip install coveralls

script: python setup.py test -a "--cov subliminal"

after_success: coveralls
